### PR TITLE
Fix: `PinataMetadata` type

### LINKED ISSUE #68: Property keyvalues cannot be assigned to PinataMetadata (ts2345)
### Issue  

Property `keyvalues` cannot be assigned to `PinataMetadata`  

```typescript
export type PinataMetadata = Record<string, string | number | null>;
```
  
Incompatible with usage from document e.g. [here](https://github.com/PinataCloud/Pinata-SDK#hashmetadata)
<hr>  

### Example  

This following code
```typescript
const metadata = {
    name: "new custom name",
    keyvalues: {
      newKey: "newValue",
      existingKey: "newValue",
      existingKeyToRemove: null,
    },
  };
const response = await pinata.hashMetadata("yourHashHere", metadata);
console.log(response);
```
  
will produce following diagnostic error `ts2345`
```
Argument of type '{ name: string; keyvalues: { newKey: string; existingKey: string; existingKeyToRemove: null; }; }' is not assignable to parameter of type 'PinataMetadata'.
  Property 'keyvalues' is incompatible with index signature.
    Type '{ newKey: string; existingKey: string; existingKeyToRemove: null; }' is not assignable to type 'string | number | null'.
      Type '{ newKey: string; existingKey: string; existingKeyToRemove: null; }' is not assignable to type 'number'. ts(2345)
```
<hr>  

### Packages
`typescript` : `4.3.5`
`@pinata/sdk` : `1.1.23`
<hr>  

### Runtime
node: `14.17.3`
<hr>  

### System
macOS: Big Sur (v 11.4)
chip: Intel Core i5

### LINKED ISSUE #76: Types:
Hi, 
quick question to your TS types:

```
export type PinataPinOptions = {
    pinataMetadata?: Record<string, string | number | null> | undefined;
    pinataOptions?: PinataOptions | undefined;
};
```

seems to be wrong as `pinataMetadata`  is validated by `validateMetadata` which expects an `name?: string` and `keyvalues: Object`. So you cannot pass typesafe the `keyvalues` as `pinataMetadata` do not accept `objects` as values.

 Would you please correct me if I'm missing some type? 
 
 Thank you all for your work! 👋

### PR DESCRIPTION
**Pull request by ernestognw**
Fixes #68
Fixes #76

## Description

According to [your docs](https://github.com/PinataCloud/Pinata-SDK#pinata-metadata), metadata has a shape as follows:

> The metadata object can consist of the following values:
> 
> - name (optional) - A custom string to use as the name for your content
> - keyvalues (optional) - An object containing up to 10 custom key / value pairs. The values can be:
> - - strings
> - - numbers (integers or decimals)
> - - dates (provided in ISO_8601 format)

However, its corresponding type is not reflecting this, causing  compilation problems when using with Typescript.

### CODE REVIEW

**Comment by rommel-pinata** [comment]
Thanks @ernestognw I'll run a couple of test and see if we can merge it!

**Comment by ernestognw** [comment]
> Thanks @ernestognw I'll run a couple of test and see if we can merge it!. Also I'll take care of the merge conflicts.

Sounds good @rommel-pinata
Let me know if you need any help :)

**Comment by rommel-pinata** [comment]
Hey @ernestognw I converted all JS to TS and applied you changes on the beta release! https://github.com/PinataCloud/Pinata-SDK/pull/130

**Comment by ernestognw** [comment]
> Hey @ernestognw I converted all JS to TS and applied you changes on the beta release! #130

Thanks @rommel-pinata :)

**Pull request closed without merging**
