### PR TITLE
Add Typescript vol.2

### PR DESCRIPTION
**Pull request by hubagaspar91**
Hey,

I have now found what I believe is a better solution (closed a previous PR), that uses jsdoc only, building on the solution by timhc22.

Added a bunch of comments to index.js, it's less pretty but it is crucial for typescript usability to export a PinataClient type for the client itself. I now do that with a @typedef. 

Tested it with my typescript project and it works perfectly.

Also added @types/node earlier, cause `tsc` was throwing errors without it.

Hope u can merge it, cause it'd be really great to start using this lib and pinata with TS too. :)

### CODE REVIEW

**Comment by hubagaspar91** [comment]
Added another commit, adding detailed @typedef comments, for properly typing the public API for typescript users, cause it was not much use with all the `any`s and `unknown`s.

I have triple-checked it, but not tested it out in action. I have, however, written all the type definitions based on the readme, so it should be accurate.

Also fixed one small error in README.md.

**Comment by polluterofminds** [comment]
Thanks @hubagaspar91! Reviewing this now.

**Comment by polluterofminds** [comment]
@hubagaspar91 would you mind adding a quick note in the README on how to use the SDK in a typescript project? I'm testing it and I don't see any type definitions, but I am also no good at Typescript so I'm sure I'm doing something wrong :)

**Comment by hubagaspar91** [comment]
@polluterofminds how are you testing it? 

The type definitions I added are written to dist/index.d.ts after running `npm run build` or simply `tsc`.

Type definitions are fully working for me right now in a TS project, where I installed my forked version of the package from a local folder, that is `npm install <PATH_TO_LOCAL_PACKAGE>`.

**Comment by polluterofminds** [comment]
Got it. This all seems to be working fine. I'll have @obo20 sign off on it then we can merge it in!

**Comment by timhc22** [comment]
Glad this was able to be sorted, I've been pretty hectic, encouraging to have seen the rest of the community able to help out. Great job @hubagaspar91 !

**Comment by hubagaspar91** [comment]
@timhc22 Sure, I'm interested, I'll PM u on twitter

**Pull request merged**
