### PR TITLE
use Infinity numeric type correctly

### PR DESCRIPTION
**Pull request by adamrhunter**
Instead of the string literal 'Infinity', use the numeric value Infinity

### CODE REVIEW

**Comment by adamrhunter** [comment]
@obo20 - anything else I need to get to get this merged?  thanks :)

**Comment by starryeyez024** [comment]
@adamrhunter thanks for submitting a PR! Is there a related issue that this solves?

**Comment by adamrhunter** [comment]
> @adamrhunter thanks for submitting a PR! Is there a related issue that this solves?

Hi @starryeyez024  - This does not solve any issues reported here.  It just fixes a typo in the code so that reserved `Infinity` is used instead of the string value 'Infinity'.  Thanks!

**Comment by rommel-pinata** [comment]
Hey @adamrhunter Thanks for your PR.

I saw your code and applied to develop branch since the code changed and it needs to run build in order to reflect your changes.

here is the [commit](https://github.com/PinataCloud/Pinata-SDK/commit/4bff6d3a6d2ca5b0d745a0ec903fdfb4ffb34a82)

**Pull request closed without merging**
