### PR TITLE
fixed require statement on pinata-sdk.js

### LINKED ISSUE #133: upload folder fialed
my program

```
const fs = require('fs');
const path = require('path');
const pinataSDK = require('@pinata/sdk');
const pinata = pinataSDK(API Key,API Secret);
async  function main(){
    const imgPath = path.join(__dirname,'..','img')
    const files = fs.readdirSync(imgPath)
    for(var i = 0;i< files.length;i++){
        console.log('Pinning to pinata ....')
        const readableStreamForFile = fs.createReadStream(imgPath+`/${files[i]}`);
        let result = await pinata.pinFileToIPFS(readableStreamForFile);
        hashes.push(result.IpfsHash);
    }
}

main();
```
I get this error when compiling

TypeError: pinataSDK is not a function
    at Object.<anonymous> (/Users/steven/Documents/Node/src/pin-to-ipfs/scripts/upload.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

### PR DESCRIPTION
**Pull request by rommel-pinata**
Fixes #133

### CODE REVIEW

**Comment by Jase-Legi** [comment]
we are good now?

**Comment by rommel-pinata** [comment]
Yes once this is merged and published you should be able to upload. One thing to check is that now you have to create an instance of the class

```
const pinataSDK = require('@pinata/sdk');
const keys = require("./key");


const pinata = new pinataSDK(keys.apiKey,keys.apiSecret);

async function exec(){
    const result = await pinata.pinFromFS("/Users/rommelberrios/Documents/pinata/Pinata-SDK/pinata.png", {pinataMetadata: {name: "different-name.jpg"}});
    console.log('result', result)
}

exec()

```

**Comment by Jase-Legi** [comment]
I saw that it's now instantiated with the "new" statement when I checked the docs this morning, it was failing when I tried to instantiate it like a new class earlier but I'll try once it's live. Btw the original post wasn't mine so I don't know if that person knows, but I had the same issue.

**Comment by rommel-pinata** [comment]
It seems both faced the same error

**Review by polluterofminds — APPROVED** [review]

**Pull request merged**
